//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: grpc/health/v1/health.proto

package com.example.trainstationapp.data.grpc.grpc.health.v1;

@kotlin.jvm.JvmName("-initializehealthCheckResponse")
inline fun healthCheckResponse(block: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthCheckResponseKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse =
  com.example.trainstationapp.data.grpc.grpc.health.v1.HealthCheckResponseKt.Dsl._create(com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.newBuilder()).apply { block() }._build()
object HealthCheckResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse = _builder.build()

    /**
     * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
     */
    var status: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.ServingStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
     */
    fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
inline fun com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.copy(block: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthCheckResponseKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse =
  com.example.trainstationapp.data.grpc.grpc.health.v1.HealthCheckResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

