//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: grpc/health/v1/health.proto

package com.example.trainstationapp.data.grpc.grpc.health.v1;

@kotlin.jvm.JvmName("-initializehealthCheckRequest")
inline fun healthCheckRequest(block: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthCheckRequestKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest =
  com.example.trainstationapp.data.grpc.grpc.health.v1.HealthCheckRequestKt.Dsl._create(com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest.newBuilder()).apply { block() }._build()
object HealthCheckRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest = _builder.build()

    /**
     * <code>string service = 1 [json_name = "service"];</code>
     */
    var service: kotlin.String
      @JvmName("getService")
      get() = _builder.getService()
      @JvmName("setService")
      set(value) {
        _builder.setService(value)
      }
    /**
     * <code>string service = 1 [json_name = "service"];</code>
     */
    fun clearService() {
      _builder.clearService()
    }
  }
}
inline fun com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest.copy(block: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthCheckRequestKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest =
  com.example.trainstationapp.data.grpc.grpc.health.v1.HealthCheckRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

