// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: auth/v1alpha1/auth.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.trainstationapp.data.grpc.auth.v1alpha1;

@kotlin.jvm.JvmName("-initializeaccount")
public inline fun account(block: com.example.trainstationapp.data.grpc.auth.v1alpha1.AccountKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account =
  com.example.trainstationapp.data.grpc.auth.v1alpha1.AccountKt.Dsl._create(com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.newBuilder()).apply { block() }._build()
/**
 * ```
 * Account are the credentials for authentication API.
 * ```
 *
 * Protobuf type `auth.v1alpha1.Account`
 */
public object AccountKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account = _builder.build()

    /**
     * ```
     **
     * ID of the provider used for this account.
     *
     * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
     * ```
     *
     * `string provider = 1 [json_name = "provider"];`
     */
    public var provider: kotlin.String
      @JvmName("getProvider")
      get() = _builder.getProvider()
      @JvmName("setProvider")
      set(value) {
        _builder.setProvider(value)
      }
    /**
     * ```
     **
     * ID of the provider used for this account.
     *
     * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
     * ```
     *
     * `string provider = 1 [json_name = "provider"];`
     */
    public fun clearProvider() {
      _builder.clearProvider()
    }

    /**
     * ```
     ** Provider's type for this account, oauth or oidc. 
     * ```
     *
     * `string type = 2 [json_name = "type"];`
     */
    public var type: kotlin.String
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * ```
     ** Provider's type for this account, oauth or oidc. 
     * ```
     *
     * `string type = 2 [json_name = "type"];`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * ```
     ** The provider account ID. 
     * ```
     *
     * `string provider_account_id = 3 [json_name = "providerAccountId"];`
     */
    public var providerAccountId: kotlin.String
      @JvmName("getProviderAccountId")
      get() = _builder.getProviderAccountId()
      @JvmName("setProviderAccountId")
      set(value) {
        _builder.setProviderAccountId(value)
      }
    /**
     * ```
     ** The provider account ID. 
     * ```
     *
     * `string provider_account_id = 3 [json_name = "providerAccountId"];`
     */
    public fun clearProviderAccountId() {
      _builder.clearProviderAccountId()
    }

    /**
     * ```
     ** The provider access_token. 
     * ```
     *
     * `string access_token = 4 [json_name = "accessToken"];`
     */
    public var accessToken: kotlin.String
      @JvmName("getAccessToken")
      get() = _builder.getAccessToken()
      @JvmName("setAccessToken")
      set(value) {
        _builder.setAccessToken(value)
      }
    /**
     * ```
     ** The provider access_token. 
     * ```
     *
     * `string access_token = 4 [json_name = "accessToken"];`
     */
    public fun clearAccessToken() {
      _builder.clearAccessToken()
    }
  }
}
public inline fun com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.copy(block: com.example.trainstationapp.data.grpc.auth.v1alpha1.AccountKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account =
  com.example.trainstationapp.data.grpc.auth.v1alpha1.AccountKt.Dsl._create(this.toBuilder()).apply { block() }._build()

