// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: auth/v1alpha1/auth.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.trainstationapp.data.grpc.auth.v1alpha1;

@kotlin.jvm.JvmName("-initializegetJWTResponse")
public inline fun getJWTResponse(block: com.example.trainstationapp.data.grpc.auth.v1alpha1.GetJWTResponseKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse =
  com.example.trainstationapp.data.grpc.auth.v1alpha1.GetJWTResponseKt.Dsl._create(com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `auth.v1alpha1.GetJWTResponse`
 */
public object GetJWTResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse = _builder.build()

    /**
     * `string token = 1 [json_name = "token"];`
     */
    public var token: kotlin.String
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * `string token = 1 [json_name = "token"];`
     */
    public fun clearToken() {
      _builder.clearToken()
    }
  }
}
public inline fun com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse.copy(block: com.example.trainstationapp.data.grpc.auth.v1alpha1.GetJWTResponseKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse =
  com.example.trainstationapp.data.grpc.auth.v1alpha1.GetJWTResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

