//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: trainstation/v1alpha1/station.proto

package com.example.trainstationapp.data.grpc.trainstation.v1alpha1;

@kotlin.jvm.JvmName("-initializegetManyStationsRequest")
public inline fun getManyStationsRequest(block: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.GetManyStationsRequestKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest =
  com.example.trainstationapp.data.grpc.trainstation.v1alpha1.GetManyStationsRequestKt.Dsl._create(com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest.newBuilder()).apply { block() }._build()
public object GetManyStationsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest = _builder.build()

    /**
     * <code>string query = 1 [json_name = "query"];</code>
     */
    public var query: kotlin.String
      @JvmName("getQuery")
      get() = _builder.getQuery()
      @JvmName("setQuery")
      set(value) {
        _builder.setQuery(value)
      }
    /**
     * <code>string query = 1 [json_name = "query"];</code>
     */
    public fun clearQuery() {
      _builder.clearQuery()
    }

    /**
     * <code>int64 limit = 2 [json_name = "limit", jstype = JS_NUMBER];</code>
     */
    public var limit: kotlin.Long
      @JvmName("getLimit")
      get() = _builder.getLimit()
      @JvmName("setLimit")
      set(value) {
        _builder.setLimit(value)
      }
    /**
     * <code>int64 limit = 2 [json_name = "limit", jstype = JS_NUMBER];</code>
     */
    public fun clearLimit() {
      _builder.clearLimit()
    }

    /**
     * <code>int64 page = 3 [json_name = "page", jstype = JS_NUMBER];</code>
     */
    public var page: kotlin.Long
      @JvmName("getPage")
      get() = _builder.getPage()
      @JvmName("setPage")
      set(value) {
        _builder.setPage(value)
      }
    /**
     * <code>int64 page = 3 [json_name = "page", jstype = JS_NUMBER];</code>
     */
    public fun clearPage() {
      _builder.clearPage()
    }

    /**
     * <code>string token = 4 [json_name = "token"];</code>
     */
    public var token: kotlin.String
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * <code>string token = 4 [json_name = "token"];</code>
     */
    public fun clearToken() {
      _builder.clearToken()
    }
  }
}
public inline fun com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest.copy(block: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.GetManyStationsRequestKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest =
  com.example.trainstationapp.data.grpc.trainstation.v1alpha1.GetManyStationsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

