// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: trainstation/v1alpha1/station.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.trainstationapp.data.grpc.trainstation.v1alpha1;

@kotlin.jvm.JvmName("-initializepaginatedStation")
public inline fun paginatedStation(block: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.PaginatedStationKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.PaginatedStation =
  com.example.trainstationapp.data.grpc.trainstation.v1alpha1.PaginatedStationKt.Dsl._create(com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.PaginatedStation.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `trainstation.v1alpha1.PaginatedStation`
 */
public object PaginatedStationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.PaginatedStation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.PaginatedStation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.PaginatedStation = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DataProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .trainstation.v1alpha1.Station data = 1 [json_name = "data"];`
     */
     public val data: com.google.protobuf.kotlin.DslList<com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station, DataProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getDataList()
      )
    /**
     * `repeated .trainstation.v1alpha1.Station data = 1 [json_name = "data"];`
     * @param value The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addData")
    public fun com.google.protobuf.kotlin.DslList<com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station, DataProxy>.add(value: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station) {
      _builder.addData(value)
    }
    /**
     * `repeated .trainstation.v1alpha1.Station data = 1 [json_name = "data"];`
     * @param value The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignData")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station, DataProxy>.plusAssign(value: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station) {
      add(value)
    }
    /**
     * `repeated .trainstation.v1alpha1.Station data = 1 [json_name = "data"];`
     * @param values The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllData")
    public fun com.google.protobuf.kotlin.DslList<com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station, DataProxy>.addAll(values: kotlin.collections.Iterable<com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station>) {
      _builder.addAllData(values)
    }
    /**
     * `repeated .trainstation.v1alpha1.Station data = 1 [json_name = "data"];`
     * @param values The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllData")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station, DataProxy>.plusAssign(values: kotlin.collections.Iterable<com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station>) {
      addAll(values)
    }
    /**
     * `repeated .trainstation.v1alpha1.Station data = 1 [json_name = "data"];`
     * @param index The index to set the value at.
     * @param value The data to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setData")
    public operator fun com.google.protobuf.kotlin.DslList<com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station, DataProxy>.set(index: kotlin.Int, value: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station) {
      _builder.setData(index, value)
    }
    /**
     * `repeated .trainstation.v1alpha1.Station data = 1 [json_name = "data"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearData")
    public fun com.google.protobuf.kotlin.DslList<com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station, DataProxy>.clear() {
      _builder.clearData()
    }

    /**
     * <code>int64 count = 2 [json_name = "count", jstype = JS_NUMBER];</code>
     */
    public var count: kotlin.Long
      @JvmName("getCount")
      get() = _builder.getCount()
      @JvmName("setCount")
      set(value) {
        _builder.setCount(value)
      }
    /**
     * `int64 count = 2 [json_name = "count", jstype = JS_NUMBER];`
     */
    public fun clearCount() {
      _builder.clearCount()
    }

    /**
     * <code>int64 total = 3 [json_name = "total", jstype = JS_NUMBER];</code>
     */
    public var total: kotlin.Long
      @JvmName("getTotal")
      get() = _builder.getTotal()
      @JvmName("setTotal")
      set(value) {
        _builder.setTotal(value)
      }
    /**
     * `int64 total = 3 [json_name = "total", jstype = JS_NUMBER];`
     */
    public fun clearTotal() {
      _builder.clearTotal()
    }

    /**
     * <code>int64 page = 4 [json_name = "page", jstype = JS_NUMBER];</code>
     */
    public var page: kotlin.Long
      @JvmName("getPage")
      get() = _builder.getPage()
      @JvmName("setPage")
      set(value) {
        _builder.setPage(value)
      }
    /**
     * `int64 page = 4 [json_name = "page", jstype = JS_NUMBER];`
     */
    public fun clearPage() {
      _builder.clearPage()
    }

    /**
     * <code>int64 page_count = 5 [json_name = "pageCount", jstype = JS_NUMBER];</code>
     */
    public var pageCount: kotlin.Long
      @JvmName("getPageCount")
      get() = _builder.getPageCount()
      @JvmName("setPageCount")
      set(value) {
        _builder.setPageCount(value)
      }
    /**
     * `int64 page_count = 5 [json_name = "pageCount", jstype = JS_NUMBER];`
     */
    public fun clearPageCount() {
      _builder.clearPageCount()
    }
  }
}
public inline fun com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.PaginatedStation.copy(block: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.PaginatedStationKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.PaginatedStation =
  com.example.trainstationapp.data.grpc.trainstation.v1alpha1.PaginatedStationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

