openapi: '3.0.3'
info:
  title: Train Station API
  description: 'This is a sample server Train Station API.'
  contact:
    email: nguyen_marc@live.fr
  license:
    name: MIT
    url: https://github.com/Darkness4/train-station/blob/main/LICENSE
  version: 1.1.0
servers:
  - url: https://train.the-end-is-never-the-end.pw/
tags:
  - name: station
    description: Operations about train stations
  - name: other
    description: Other type of operations
paths:
  /api/stations/:
    $ref: ./routes/api/stations.yaml
  /api/stations/{id}:
    $ref: ./routes/api/stations/{id}.yaml
  /api/stations/{id}/makeFavorite:
    $ref: ./routes/api/stations/{id}/makeFavorite.yaml
  /:
    $ref: ./routes/root.yaml
  /healthz:
    $ref: ./routes/healthz.yaml
  /openapi:
    $ref: ./routes/openapi.yaml

components:
  schemas:
    Geometry:
      $ref: ./entities/Geometry.yaml
    Fields:
      $ref: ./entities/Fields.yaml
    Station:
      $ref: ./entities/Station.yaml
    PaginatedStation:
      $ref: ./entities/PaginatedStation.yaml
    Error:
      $ref: ./entities/Error.yaml

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
