// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainstation/v1alpha1/station.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.trainstationapp.data.grpc.trainstation.v1alpha1;

@kotlin.jvm.JvmName("-initializegetManyStationsRequest")
public inline fun getManyStationsRequest(block: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.GetManyStationsRequestKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest =
  com.example.trainstationapp.data.grpc.trainstation.v1alpha1.GetManyStationsRequestKt.Dsl._create(com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `trainstation.v1alpha1.GetManyStationsRequest`
 */
public object GetManyStationsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest = _builder.build()

    /**
     * `string query = 1 [json_name = "query"];`
     */
    public var query: kotlin.String
      @kotlin.jvm.JvmName("getQuery")
        get() = _builder.query
      @kotlin.jvm.JvmName("setQuery")
        set(value) {
        _builder.query = value
      }
    /**
     * `string query = 1 [json_name = "query"];`
     */
    public fun clearQuery() {
      _builder.clearQuery()
    }

    /**
     * `int64 limit = 2 [json_name = "limit"];`
     */
    public var limit: kotlin.Long
      @kotlin.jvm.JvmName("getLimit")
        get() = _builder.limit
      @kotlin.jvm.JvmName("setLimit")
        set(value) {
        _builder.limit = value
      }
    /**
     * `int64 limit = 2 [json_name = "limit"];`
     */
    public fun clearLimit() {
      _builder.clearLimit()
    }

    /**
     * `int64 page = 3 [json_name = "page"];`
     */
    public var page: kotlin.Long
      @kotlin.jvm.JvmName("getPage")
        get() = _builder.page
      @kotlin.jvm.JvmName("setPage")
        set(value) {
        _builder.page = value
      }
    /**
     * `int64 page = 3 [json_name = "page"];`
     */
    public fun clearPage() {
      _builder.clearPage()
    }
  }
}
public inline fun com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest.copy(block: `com.example.trainstationapp.data.grpc.trainstation.v1alpha1`.GetManyStationsRequestKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest =
  `com.example.trainstationapp.data.grpc.trainstation.v1alpha1`.GetManyStationsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
