// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: trainstation/v1alpha1/station.proto
//
package com.example.trainstationapp.`data`.grpc.trainstation.v1alpha1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

/**
 *  StationAPI handles train stations from the SNCF.
 *
 *  The API needs the user to be authenticated via the AuthAPI.
 */
public class StationAPIClient(
  private val client: ProtocolClientInterface,
) : StationAPIClientInterface {
  /**
   *  GetManyStations fetch a paginated list of station.
   */
  override suspend fun getManyStations(request: StationProto.GetManyStationsRequest, headers: Headers): ResponseMessage<StationProto.GetManyStationsResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "trainstation.v1alpha1.StationAPI/GetManyStations",
      com.example.trainstationapp.`data`.grpc.trainstation.v1alpha1.StationProto.GetManyStationsRequest::class,
      com.example.trainstationapp.`data`.grpc.trainstation.v1alpha1.StationProto.GetManyStationsResponse::class,
      StreamType.UNARY,
    ),
  )


  /**
   *  GetOneStation fetches the details of a station.
   */
  override suspend fun getOneStation(request: StationProto.GetOneStationRequest, headers: Headers): ResponseMessage<StationProto.GetOneStationResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "trainstation.v1alpha1.StationAPI/GetOneStation",
      com.example.trainstationapp.`data`.grpc.trainstation.v1alpha1.StationProto.GetOneStationRequest::class,
      com.example.trainstationapp.`data`.grpc.trainstation.v1alpha1.StationProto.GetOneStationResponse::class,
      StreamType.UNARY,
    ),
  )


  /**
   *  SetFavoriteOneStation set a station to favorite for a user.
   */
  override suspend fun setFavoriteOneStation(request: StationProto.SetFavoriteOneStationRequest, headers: Headers): ResponseMessage<StationProto.SetFavoriteOneStationResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "trainstation.v1alpha1.StationAPI/SetFavoriteOneStation",
      com.example.trainstationapp.`data`.grpc.trainstation.v1alpha1.StationProto.SetFavoriteOneStationRequest::class,
      com.example.trainstationapp.`data`.grpc.trainstation.v1alpha1.StationProto.SetFavoriteOneStationResponse::class,
      StreamType.UNARY,
    ),
  )

}
