// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: trainstation/v1alpha1/station.proto
//
package com.example.trainstationapp.`data`.grpc.trainstation.v1alpha1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  StationAPI handles train stations from the SNCF.
 *
 *  The API needs the user to be authenticated via the AuthAPI.
 */
public interface StationAPIClientInterface {
  /**
   *  GetManyStations fetch a paginated list of station.
   */
  public suspend fun getManyStations(request: StationProto.GetManyStationsRequest, headers: Headers = emptyMap()): ResponseMessage<StationProto.GetManyStationsResponse>

  /**
   *  GetOneStation fetches the details of a station.
   */
  public suspend fun getOneStation(request: StationProto.GetOneStationRequest, headers: Headers = emptyMap()): ResponseMessage<StationProto.GetOneStationResponse>

  /**
   *  SetFavoriteOneStation set a station to favorite for a user.
   */
  public suspend fun setFavoriteOneStation(request: StationProto.SetFavoriteOneStationRequest, headers: Headers = emptyMap()): ResponseMessage<StationProto.SetFavoriteOneStationResponse>
}
