// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainstation/v1alpha1/station.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.trainstationapp.data.grpc.trainstation.v1alpha1;

@kotlin.jvm.JvmName("-initializestation")
public inline fun station(block: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station =
  com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationKt.Dsl._create(com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `trainstation.v1alpha1.Station`
 */
public object StationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string commune = 2 [json_name = "commune"];`
     */
    public var commune: kotlin.String
      @kotlin.jvm.JvmName("getCommune")
        get() = _builder.commune
      @kotlin.jvm.JvmName("setCommune")
        set(value) {
        _builder.commune = value
      }
    /**
     * `string commune = 2 [json_name = "commune"];`
     */
    public fun clearCommune() {
      _builder.clearCommune()
    }

    /**
     * `double y_wgs84 = 3 [json_name = "yWgs84"];`
     */
    public var yWgs84: kotlin.Double
      @kotlin.jvm.JvmName("getYWgs84")
        get() = _builder.yWgs84
      @kotlin.jvm.JvmName("setYWgs84")
        set(value) {
        _builder.yWgs84 = value
      }
    /**
     * `double y_wgs84 = 3 [json_name = "yWgs84"];`
     */
    public fun clearYWgs84() {
      _builder.clearYWgs84()
    }

    /**
     * `double x_wgs84 = 4 [json_name = "xWgs84"];`
     */
    public var xWgs84: kotlin.Double
      @kotlin.jvm.JvmName("getXWgs84")
        get() = _builder.xWgs84
      @kotlin.jvm.JvmName("setXWgs84")
        set(value) {
        _builder.xWgs84 = value
      }
    /**
     * `double x_wgs84 = 4 [json_name = "xWgs84"];`
     */
    public fun clearXWgs84() {
      _builder.clearXWgs84()
    }

    /**
     * `string libelle = 5 [json_name = "libelle"];`
     */
    public var libelle: kotlin.String
      @kotlin.jvm.JvmName("getLibelle")
        get() = _builder.libelle
      @kotlin.jvm.JvmName("setLibelle")
        set(value) {
        _builder.libelle = value
      }
    /**
     * `string libelle = 5 [json_name = "libelle"];`
     */
    public fun clearLibelle() {
      _builder.clearLibelle()
    }

    /**
     * `string idgaia = 6 [json_name = "idgaia"];`
     */
    public var idgaia: kotlin.String
      @kotlin.jvm.JvmName("getIdgaia")
        get() = _builder.idgaia
      @kotlin.jvm.JvmName("setIdgaia")
        set(value) {
        _builder.idgaia = value
      }
    /**
     * `string idgaia = 6 [json_name = "idgaia"];`
     */
    public fun clearIdgaia() {
      _builder.clearIdgaia()
    }

    /**
     * `string voyageurs = 7 [json_name = "voyageurs"];`
     */
    public var voyageurs: kotlin.String
      @kotlin.jvm.JvmName("getVoyageurs")
        get() = _builder.voyageurs
      @kotlin.jvm.JvmName("setVoyageurs")
        set(value) {
        _builder.voyageurs = value
      }
    /**
     * `string voyageurs = 7 [json_name = "voyageurs"];`
     */
    public fun clearVoyageurs() {
      _builder.clearVoyageurs()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class GeoPoint2DProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated double geo_point_2d = 8 [json_name = "geoPoint2d"];`
     */
     public val geoPoint2D: com.google.protobuf.kotlin.DslList<kotlin.Double, GeoPoint2DProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.geoPoint2DList
      )
    /**
     * `repeated double geo_point_2d = 8 [json_name = "geoPoint2d"];`
     * @param value The geoPoint2d to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addGeoPoint2D")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, GeoPoint2DProxy>.add(value: kotlin.Double) {
      _builder.addGeoPoint2D(value)
    }/**
     * `repeated double geo_point_2d = 8 [json_name = "geoPoint2d"];`
     * @param value The geoPoint2d to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignGeoPoint2D")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, GeoPoint2DProxy>.plusAssign(value: kotlin.Double) {
      add(value)
    }/**
     * `repeated double geo_point_2d = 8 [json_name = "geoPoint2d"];`
     * @param values The geoPoint2d to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllGeoPoint2D")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, GeoPoint2DProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Double>) {
      _builder.addAllGeoPoint2D(values)
    }/**
     * `repeated double geo_point_2d = 8 [json_name = "geoPoint2d"];`
     * @param values The geoPoint2d to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllGeoPoint2D")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, GeoPoint2DProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Double>) {
      addAll(values)
    }/**
     * `repeated double geo_point_2d = 8 [json_name = "geoPoint2d"];`
     * @param index The index to set the value at.
     * @param value The geoPoint2d to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setGeoPoint2D")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, GeoPoint2DProxy>.set(index: kotlin.Int, value: kotlin.Double) {
      _builder.setGeoPoint2D(index, value)
    }/**
     * `repeated double geo_point_2d = 8 [json_name = "geoPoint2d"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearGeoPoint2D")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, GeoPoint2DProxy>.clear() {
      _builder.clearGeoPoint2D()
    }
    /**
     * `string code_ligne = 9 [json_name = "codeLigne"];`
     */
    public var codeLigne: kotlin.String
      @kotlin.jvm.JvmName("getCodeLigne")
        get() = _builder.codeLigne
      @kotlin.jvm.JvmName("setCodeLigne")
        set(value) {
        _builder.codeLigne = value
      }
    /**
     * `string code_ligne = 9 [json_name = "codeLigne"];`
     */
    public fun clearCodeLigne() {
      _builder.clearCodeLigne()
    }

    /**
     * `double x_l93 = 10 [json_name = "xL93"];`
     */
    public var xL93: kotlin.Double
      @kotlin.jvm.JvmName("getXL93")
        get() = _builder.xL93
      @kotlin.jvm.JvmName("setXL93")
        set(value) {
        _builder.xL93 = value
      }
    /**
     * `double x_l93 = 10 [json_name = "xL93"];`
     */
    public fun clearXL93() {
      _builder.clearXL93()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CGeoProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated double c_geo = 11 [json_name = "cGeo"];`
     */
     public val cGeo: com.google.protobuf.kotlin.DslList<kotlin.Double, CGeoProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.cGeoList
      )
    /**
     * `repeated double c_geo = 11 [json_name = "cGeo"];`
     * @param value The cGeo to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addCGeo")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, CGeoProxy>.add(value: kotlin.Double) {
      _builder.addCGeo(value)
    }/**
     * `repeated double c_geo = 11 [json_name = "cGeo"];`
     * @param value The cGeo to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignCGeo")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, CGeoProxy>.plusAssign(value: kotlin.Double) {
      add(value)
    }/**
     * `repeated double c_geo = 11 [json_name = "cGeo"];`
     * @param values The cGeo to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllCGeo")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, CGeoProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Double>) {
      _builder.addAllCGeo(values)
    }/**
     * `repeated double c_geo = 11 [json_name = "cGeo"];`
     * @param values The cGeo to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllCGeo")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, CGeoProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Double>) {
      addAll(values)
    }/**
     * `repeated double c_geo = 11 [json_name = "cGeo"];`
     * @param index The index to set the value at.
     * @param value The cGeo to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setCGeo")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, CGeoProxy>.set(index: kotlin.Int, value: kotlin.Double) {
      _builder.setCGeo(index, value)
    }/**
     * `repeated double c_geo = 11 [json_name = "cGeo"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearCGeo")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, CGeoProxy>.clear() {
      _builder.clearCGeo()
    }
    /**
     * `int64 rg_troncon = 12 [json_name = "rgTroncon"];`
     */
    public var rgTroncon: kotlin.Long
      @kotlin.jvm.JvmName("getRgTroncon")
        get() = _builder.rgTroncon
      @kotlin.jvm.JvmName("setRgTroncon")
        set(value) {
        _builder.rgTroncon = value
      }
    /**
     * `int64 rg_troncon = 12 [json_name = "rgTroncon"];`
     */
    public fun clearRgTroncon() {
      _builder.clearRgTroncon()
    }

    /**
     * `.trainstation.v1alpha1.Geometry geo_shape = 13 [json_name = "geoShape"];`
     */
    public var geoShape: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Geometry
      @kotlin.jvm.JvmName("getGeoShape")
        get() = _builder.geoShape
      @kotlin.jvm.JvmName("setGeoShape")
        set(value) {
        _builder.geoShape = value
      }
    /**
     * `.trainstation.v1alpha1.Geometry geo_shape = 13 [json_name = "geoShape"];`
     */
    public fun clearGeoShape() {
      _builder.clearGeoShape()
    }
    /**
     * `.trainstation.v1alpha1.Geometry geo_shape = 13 [json_name = "geoShape"];`
     * @return Whether the geoShape field is set.
     */
    public fun hasGeoShape(): kotlin.Boolean {
      return _builder.hasGeoShape()
    }

    public val StationKt.Dsl.geoShapeOrNull: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Geometry?
      get() = _builder.geoShapeOrNull

    /**
     * `string pk = 14 [json_name = "pk"];`
     */
    public var pk: kotlin.String
      @kotlin.jvm.JvmName("getPk")
        get() = _builder.pk
      @kotlin.jvm.JvmName("setPk")
        set(value) {
        _builder.pk = value
      }
    /**
     * `string pk = 14 [json_name = "pk"];`
     */
    public fun clearPk() {
      _builder.clearPk()
    }

    /**
     * `int64 idreseau = 15 [json_name = "idreseau"];`
     */
    public var idreseau: kotlin.Long
      @kotlin.jvm.JvmName("getIdreseau")
        get() = _builder.idreseau
      @kotlin.jvm.JvmName("setIdreseau")
        set(value) {
        _builder.idreseau = value
      }
    /**
     * `int64 idreseau = 15 [json_name = "idreseau"];`
     */
    public fun clearIdreseau() {
      _builder.clearIdreseau()
    }

    /**
     * `string departemen = 16 [json_name = "departemen"];`
     */
    public var departemen: kotlin.String
      @kotlin.jvm.JvmName("getDepartemen")
        get() = _builder.departemen
      @kotlin.jvm.JvmName("setDepartemen")
        set(value) {
        _builder.departemen = value
      }
    /**
     * `string departemen = 16 [json_name = "departemen"];`
     */
    public fun clearDepartemen() {
      _builder.clearDepartemen()
    }

    /**
     * `double y_l93 = 17 [json_name = "yL93"];`
     */
    public var yL93: kotlin.Double
      @kotlin.jvm.JvmName("getYL93")
        get() = _builder.yL93
      @kotlin.jvm.JvmName("setYL93")
        set(value) {
        _builder.yL93 = value
      }
    /**
     * `double y_l93 = 17 [json_name = "yL93"];`
     */
    public fun clearYL93() {
      _builder.clearYL93()
    }

    /**
     * `string fret = 18 [json_name = "fret"];`
     */
    public var fret: kotlin.String
      @kotlin.jvm.JvmName("getFret")
        get() = _builder.fret
      @kotlin.jvm.JvmName("setFret")
        set(value) {
        _builder.fret = value
      }
    /**
     * `string fret = 18 [json_name = "fret"];`
     */
    public fun clearFret() {
      _builder.clearFret()
    }

    /**
     * `bool is_favorite = 19 [json_name = "isFavorite"];`
     */
    public var isFavorite: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsFavorite")
        get() = _builder.isFavorite
      @kotlin.jvm.JvmName("setIsFavorite")
        set(value) {
        _builder.isFavorite = value
      }
    /**
     * `bool is_favorite = 19 [json_name = "isFavorite"];`
     */
    public fun clearIsFavorite() {
      _builder.clearIsFavorite()
    }
  }
}
public inline fun com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station.copy(block: `com.example.trainstationapp.data.grpc.trainstation.v1alpha1`.StationKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Station =
  `com.example.trainstationapp.data.grpc.trainstation.v1alpha1`.StationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.StationOrBuilder.geoShapeOrNull: com.example.trainstationapp.data.grpc.trainstation.v1alpha1.StationProto.Geometry?
  get() = if (hasGeoShape()) getGeoShape() else null

