graph TB

  ServiceLocator -- inject --> StationDataSource
  ServiceLocator -- inject --> StationRepository
  ServiceLocator -- inject --> AuthService
  ServiceLocator -- inject --> FirebaseApp
  ServiceLocator -- inject --> AuthClient

  subgraph "Externals"
    FirebaseApp
    AuthClient
  end

  FirebaseApp --> AuthService
  AuthClient --> AuthService

	subgraph "Core"
    ServiceLocator
  end

  subgraph "Data"
    StationDataSource
    StationRepositoryImpl
    Models

    StationDataSource --> StationRepositoryImpl
  end

  StationRepositoryImpl -. implements .-> StationRepository

  subgraph "Domain"
    AuthService -- permits --> StationRepository
    StationRepository

    Entities
  end

  StationRepository --> TrainStationController

  subgraph "Presentation"
    TrainStationController
    RootController

    DTOs
  end

  TrainStationController -- serve --> Client
  RootController -- serve --> Client
