//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: auth/v1alpha1/auth.proto

package com.example.trainstationapp.data.grpc.auth.v1alpha1;

@kotlin.jvm.JvmName("-initializeaccount")
inline fun account(block: com.example.trainstationapp.data.grpc.auth.v1alpha1.AccountKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account =
  com.example.trainstationapp.data.grpc.auth.v1alpha1.AccountKt.Dsl._create(com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.newBuilder()).apply { block() }._build()
object AccountKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account = _builder.build()

    /**
     * <pre>
     **
     * ID of the provider used for this account.
     * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
     * </pre>
     *
     * <code>string provider = 1 [json_name = "provider"];</code>
     */
    var provider: kotlin.String
      @JvmName("getProvider")
      get() = _builder.getProvider()
      @JvmName("setProvider")
      set(value) {
        _builder.setProvider(value)
      }
    /**
     * <pre>
     **
     * ID of the provider used for this account.
     * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
     * </pre>
     *
     * <code>string provider = 1 [json_name = "provider"];</code>
     */
    fun clearProvider() {
      _builder.clearProvider()
    }

    /**
     * <pre>
     ** Provider's type for this account, oauth or oidc. 
     * </pre>
     *
     * <code>string type = 2 [json_name = "type"];</code>
     */
    var type: kotlin.String
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <pre>
     ** Provider's type for this account, oauth or oidc. 
     * </pre>
     *
     * <code>string type = 2 [json_name = "type"];</code>
     */
    fun clearType() {
      _builder.clearType()
    }

    /**
     * <pre>
     ** The provider account ID. 
     * </pre>
     *
     * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
     */
    var providerAccountId: kotlin.String
      @JvmName("getProviderAccountId")
      get() = _builder.getProviderAccountId()
      @JvmName("setProviderAccountId")
      set(value) {
        _builder.setProviderAccountId(value)
      }
    /**
     * <pre>
     ** The provider account ID. 
     * </pre>
     *
     * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
     */
    fun clearProviderAccountId() {
      _builder.clearProviderAccountId()
    }

    /**
     * <pre>
     ** The provider access_token. 
     * </pre>
     *
     * <code>string access_token = 4 [json_name = "accessToken"];</code>
     */
    var accessToken: kotlin.String
      @JvmName("getAccessToken")
      get() = _builder.getAccessToken()
      @JvmName("setAccessToken")
      set(value) {
        _builder.setAccessToken(value)
      }
    /**
     * <pre>
     ** The provider access_token. 
     * </pre>
     *
     * <code>string access_token = 4 [json_name = "accessToken"];</code>
     */
    fun clearAccessToken() {
      _builder.clearAccessToken()
    }
  }
}
inline fun com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.copy(block: com.example.trainstationapp.data.grpc.auth.v1alpha1.AccountKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account =
  com.example.trainstationapp.data.grpc.auth.v1alpha1.AccountKt.Dsl._create(this.toBuilder()).apply { block() }._build()

