// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/v1alpha1/auth.proto

package com.example.trainstationapp.data.grpc.auth.v1alpha1;

public final class AuthProto {
  private AuthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.v1alpha1.Account)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     **
     * ID of the provider used for this account.
     * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
     * </pre>
     *
     * <code>string provider = 1 [json_name = "provider"];</code>
     * @return The provider.
     */
    java.lang.String getProvider();
    /**
     * <pre>
     **
     * ID of the provider used for this account.
     * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
     * </pre>
     *
     * <code>string provider = 1 [json_name = "provider"];</code>
     * @return The bytes for provider.
     */
    com.google.protobuf.ByteString
        getProviderBytes();

    /**
     * <pre>
     ** Provider's type for this account, oauth or oidc. 
     * </pre>
     *
     * <code>string type = 2 [json_name = "type"];</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <pre>
     ** Provider's type for this account, oauth or oidc. 
     * </pre>
     *
     * <code>string type = 2 [json_name = "type"];</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     ** The provider account ID. 
     * </pre>
     *
     * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
     * @return The providerAccountId.
     */
    java.lang.String getProviderAccountId();
    /**
     * <pre>
     ** The provider account ID. 
     * </pre>
     *
     * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
     * @return The bytes for providerAccountId.
     */
    com.google.protobuf.ByteString
        getProviderAccountIdBytes();

    /**
     * <pre>
     ** The provider access_token. 
     * </pre>
     *
     * <code>string access_token = 4 [json_name = "accessToken"];</code>
     * @return The accessToken.
     */
    java.lang.String getAccessToken();
    /**
     * <pre>
     ** The provider access_token. 
     * </pre>
     *
     * <code>string access_token = 4 [json_name = "accessToken"];</code>
     * @return The bytes for accessToken.
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();
  }
  /**
   * <pre>
   * Account are the credentials for authentication API.
   * </pre>
   *
   * Protobuf type {@code auth.v1alpha1.Account}
   */
  public  static final class Account extends
      com.google.protobuf.GeneratedMessageLite<
          Account, Account.Builder> implements
      // @@protoc_insertion_point(message_implements:auth.v1alpha1.Account)
      AccountOrBuilder {
    private Account() {
      provider_ = "";
      type_ = "";
      providerAccountId_ = "";
      accessToken_ = "";
    }
    public static final int PROVIDER_FIELD_NUMBER = 1;
    private java.lang.String provider_;
    /**
     * <pre>
     **
     * ID of the provider used for this account.
     * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
     * </pre>
     *
     * <code>string provider = 1 [json_name = "provider"];</code>
     * @return The provider.
     */
    @java.lang.Override
    public java.lang.String getProvider() {
      return provider_;
    }
    /**
     * <pre>
     **
     * ID of the provider used for this account.
     * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
     * </pre>
     *
     * <code>string provider = 1 [json_name = "provider"];</code>
     * @return The bytes for provider.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProviderBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(provider_);
    }
    /**
     * <pre>
     **
     * ID of the provider used for this account.
     * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
     * </pre>
     *
     * <code>string provider = 1 [json_name = "provider"];</code>
     * @param value The provider to set.
     */
    private void setProvider(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      provider_ = value;
    }
    /**
     * <pre>
     **
     * ID of the provider used for this account.
     * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
     * </pre>
     *
     * <code>string provider = 1 [json_name = "provider"];</code>
     */
    private void clearProvider() {
      
      provider_ = getDefaultInstance().getProvider();
    }
    /**
     * <pre>
     **
     * ID of the provider used for this account.
     * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
     * </pre>
     *
     * <code>string provider = 1 [json_name = "provider"];</code>
     * @param value The bytes for provider to set.
     */
    private void setProviderBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      provider_ = value.toStringUtf8();
      
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private java.lang.String type_;
    /**
     * <pre>
     ** Provider's type for this account, oauth or oidc. 
     * </pre>
     *
     * <code>string type = 2 [json_name = "type"];</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      return type_;
    }
    /**
     * <pre>
     ** Provider's type for this account, oauth or oidc. 
     * </pre>
     *
     * <code>string type = 2 [json_name = "type"];</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(type_);
    }
    /**
     * <pre>
     ** Provider's type for this account, oauth or oidc. 
     * </pre>
     *
     * <code>string type = 2 [json_name = "type"];</code>
     * @param value The type to set.
     */
    private void setType(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      type_ = value;
    }
    /**
     * <pre>
     ** Provider's type for this account, oauth or oidc. 
     * </pre>
     *
     * <code>string type = 2 [json_name = "type"];</code>
     */
    private void clearType() {
      
      type_ = getDefaultInstance().getType();
    }
    /**
     * <pre>
     ** Provider's type for this account, oauth or oidc. 
     * </pre>
     *
     * <code>string type = 2 [json_name = "type"];</code>
     * @param value The bytes for type to set.
     */
    private void setTypeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      type_ = value.toStringUtf8();
      
    }

    public static final int PROVIDER_ACCOUNT_ID_FIELD_NUMBER = 3;
    private java.lang.String providerAccountId_;
    /**
     * <pre>
     ** The provider account ID. 
     * </pre>
     *
     * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
     * @return The providerAccountId.
     */
    @java.lang.Override
    public java.lang.String getProviderAccountId() {
      return providerAccountId_;
    }
    /**
     * <pre>
     ** The provider account ID. 
     * </pre>
     *
     * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
     * @return The bytes for providerAccountId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProviderAccountIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(providerAccountId_);
    }
    /**
     * <pre>
     ** The provider account ID. 
     * </pre>
     *
     * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
     * @param value The providerAccountId to set.
     */
    private void setProviderAccountId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      providerAccountId_ = value;
    }
    /**
     * <pre>
     ** The provider account ID. 
     * </pre>
     *
     * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
     */
    private void clearProviderAccountId() {
      
      providerAccountId_ = getDefaultInstance().getProviderAccountId();
    }
    /**
     * <pre>
     ** The provider account ID. 
     * </pre>
     *
     * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
     * @param value The bytes for providerAccountId to set.
     */
    private void setProviderAccountIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      providerAccountId_ = value.toStringUtf8();
      
    }

    public static final int ACCESS_TOKEN_FIELD_NUMBER = 4;
    private java.lang.String accessToken_;
    /**
     * <pre>
     ** The provider access_token. 
     * </pre>
     *
     * <code>string access_token = 4 [json_name = "accessToken"];</code>
     * @return The accessToken.
     */
    @java.lang.Override
    public java.lang.String getAccessToken() {
      return accessToken_;
    }
    /**
     * <pre>
     ** The provider access_token. 
     * </pre>
     *
     * <code>string access_token = 4 [json_name = "accessToken"];</code>
     * @return The bytes for accessToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(accessToken_);
    }
    /**
     * <pre>
     ** The provider access_token. 
     * </pre>
     *
     * <code>string access_token = 4 [json_name = "accessToken"];</code>
     * @param value The accessToken to set.
     */
    private void setAccessToken(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      accessToken_ = value;
    }
    /**
     * <pre>
     ** The provider access_token. 
     * </pre>
     *
     * <code>string access_token = 4 [json_name = "accessToken"];</code>
     */
    private void clearAccessToken() {
      
      accessToken_ = getDefaultInstance().getAccessToken();
    }
    /**
     * <pre>
     ** The provider access_token. 
     * </pre>
     *
     * <code>string access_token = 4 [json_name = "accessToken"];</code>
     * @param value The bytes for accessToken to set.
     */
    private void setAccessTokenBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      accessToken_ = value.toStringUtf8();
      
    }

    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Account are the credentials for authentication API.
     * </pre>
     *
     * Protobuf type {@code auth.v1alpha1.Account}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account, Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.v1alpha1.Account)
        com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.AccountOrBuilder {
      // Construct using com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       **
       * ID of the provider used for this account.
       * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
       * </pre>
       *
       * <code>string provider = 1 [json_name = "provider"];</code>
       * @return The provider.
       */
      @java.lang.Override
      public java.lang.String getProvider() {
        return instance.getProvider();
      }
      /**
       * <pre>
       **
       * ID of the provider used for this account.
       * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
       * </pre>
       *
       * <code>string provider = 1 [json_name = "provider"];</code>
       * @return The bytes for provider.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getProviderBytes() {
        return instance.getProviderBytes();
      }
      /**
       * <pre>
       **
       * ID of the provider used for this account.
       * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
       * </pre>
       *
       * <code>string provider = 1 [json_name = "provider"];</code>
       * @param value The provider to set.
       * @return This builder for chaining.
       */
      public Builder setProvider(
          java.lang.String value) {
        copyOnWrite();
        instance.setProvider(value);
        return this;
      }
      /**
       * <pre>
       **
       * ID of the provider used for this account.
       * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
       * </pre>
       *
       * <code>string provider = 1 [json_name = "provider"];</code>
       * @return This builder for chaining.
       */
      public Builder clearProvider() {
        copyOnWrite();
        instance.clearProvider();
        return this;
      }
      /**
       * <pre>
       **
       * ID of the provider used for this account.
       * Based on the ID of the provider, it will check the access token on the OAuth/OIDC Provider.
       * </pre>
       *
       * <code>string provider = 1 [json_name = "provider"];</code>
       * @param value The bytes for provider to set.
       * @return This builder for chaining.
       */
      public Builder setProviderBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setProviderBytes(value);
        return this;
      }

      /**
       * <pre>
       ** Provider's type for this account, oauth or oidc. 
       * </pre>
       *
       * <code>string type = 2 [json_name = "type"];</code>
       * @return The type.
       */
      @java.lang.Override
      public java.lang.String getType() {
        return instance.getType();
      }
      /**
       * <pre>
       ** Provider's type for this account, oauth or oidc. 
       * </pre>
       *
       * <code>string type = 2 [json_name = "type"];</code>
       * @return The bytes for type.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTypeBytes() {
        return instance.getTypeBytes();
      }
      /**
       * <pre>
       ** Provider's type for this account, oauth or oidc. 
       * </pre>
       *
       * <code>string type = 2 [json_name = "type"];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <pre>
       ** Provider's type for this account, oauth or oidc. 
       * </pre>
       *
       * <code>string type = 2 [json_name = "type"];</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }
      /**
       * <pre>
       ** Provider's type for this account, oauth or oidc. 
       * </pre>
       *
       * <code>string type = 2 [json_name = "type"];</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTypeBytes(value);
        return this;
      }

      /**
       * <pre>
       ** The provider account ID. 
       * </pre>
       *
       * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
       * @return The providerAccountId.
       */
      @java.lang.Override
      public java.lang.String getProviderAccountId() {
        return instance.getProviderAccountId();
      }
      /**
       * <pre>
       ** The provider account ID. 
       * </pre>
       *
       * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
       * @return The bytes for providerAccountId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getProviderAccountIdBytes() {
        return instance.getProviderAccountIdBytes();
      }
      /**
       * <pre>
       ** The provider account ID. 
       * </pre>
       *
       * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
       * @param value The providerAccountId to set.
       * @return This builder for chaining.
       */
      public Builder setProviderAccountId(
          java.lang.String value) {
        copyOnWrite();
        instance.setProviderAccountId(value);
        return this;
      }
      /**
       * <pre>
       ** The provider account ID. 
       * </pre>
       *
       * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearProviderAccountId() {
        copyOnWrite();
        instance.clearProviderAccountId();
        return this;
      }
      /**
       * <pre>
       ** The provider account ID. 
       * </pre>
       *
       * <code>string provider_account_id = 3 [json_name = "providerAccountId"];</code>
       * @param value The bytes for providerAccountId to set.
       * @return This builder for chaining.
       */
      public Builder setProviderAccountIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setProviderAccountIdBytes(value);
        return this;
      }

      /**
       * <pre>
       ** The provider access_token. 
       * </pre>
       *
       * <code>string access_token = 4 [json_name = "accessToken"];</code>
       * @return The accessToken.
       */
      @java.lang.Override
      public java.lang.String getAccessToken() {
        return instance.getAccessToken();
      }
      /**
       * <pre>
       ** The provider access_token. 
       * </pre>
       *
       * <code>string access_token = 4 [json_name = "accessToken"];</code>
       * @return The bytes for accessToken.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        return instance.getAccessTokenBytes();
      }
      /**
       * <pre>
       ** The provider access_token. 
       * </pre>
       *
       * <code>string access_token = 4 [json_name = "accessToken"];</code>
       * @param value The accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessToken(
          java.lang.String value) {
        copyOnWrite();
        instance.setAccessToken(value);
        return this;
      }
      /**
       * <pre>
       ** The provider access_token. 
       * </pre>
       *
       * <code>string access_token = 4 [json_name = "accessToken"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessToken() {
        copyOnWrite();
        instance.clearAccessToken();
        return this;
      }
      /**
       * <pre>
       ** The provider access_token. 
       * </pre>
       *
       * <code>string access_token = 4 [json_name = "accessToken"];</code>
       * @param value The bytes for accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAccessTokenBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:auth.v1alpha1.Account)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "provider_",
              "type_",
              "providerAccountId_",
              "accessToken_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:auth.v1alpha1.Account)
    private static final com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account DEFAULT_INSTANCE;
    static {
      Account defaultInstance = new Account();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Account.class, defaultInstance);
    }

    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Account> PARSER;

    public static com.google.protobuf.Parser<Account> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetJWTRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.v1alpha1.GetJWTRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
     * @return Whether the account field is set.
     */
    boolean hasAccount();
    /**
     * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
     * @return The account.
     */
    com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account getAccount();
  }
  /**
   * Protobuf type {@code auth.v1alpha1.GetJWTRequest}
   */
  public  static final class GetJWTRequest extends
      com.google.protobuf.GeneratedMessageLite<
          GetJWTRequest, GetJWTRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:auth.v1alpha1.GetJWTRequest)
      GetJWTRequestOrBuilder {
    private GetJWTRequest() {
    }
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account account_;
    /**
     * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
     */
    @java.lang.Override
    public boolean hasAccount() {
      return account_ != null;
    }
    /**
     * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
     */
    @java.lang.Override
    public com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account getAccount() {
      return account_ == null ? com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.getDefaultInstance() : account_;
    }
    /**
     * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
     */
    private void setAccount(com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account value) {
      value.getClass();
  account_ = value;
      
      }
    /**
     * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeAccount(com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account value) {
      value.getClass();
  if (account_ != null &&
          account_ != com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.getDefaultInstance()) {
        account_ =
          com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.newBuilder(account_).mergeFrom(value).buildPartial();
      } else {
        account_ = value;
      }
      
    }
    /**
     * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
     */
    private void clearAccount() {  account_ = null;
      
    }

    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code auth.v1alpha1.GetJWTRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.v1alpha1.GetJWTRequest)
        com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequestOrBuilder {
      // Construct using com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
       */
      @java.lang.Override
      public boolean hasAccount() {
        return instance.hasAccount();
      }
      /**
       * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
       */
      @java.lang.Override
      public com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account getAccount() {
        return instance.getAccount();
      }
      /**
       * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
       */
      public Builder setAccount(com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account value) {
        copyOnWrite();
        instance.setAccount(value);
        return this;
        }
      /**
       * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
       */
      public Builder setAccount(
          com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account.Builder builderForValue) {
        copyOnWrite();
        instance.setAccount(builderForValue.build());
        return this;
      }
      /**
       * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
       */
      public Builder mergeAccount(com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.Account value) {
        copyOnWrite();
        instance.mergeAccount(value);
        return this;
      }
      /**
       * <code>.auth.v1alpha1.Account account = 1 [json_name = "account"];</code>
       */
      public Builder clearAccount() {  copyOnWrite();
        instance.clearAccount();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:auth.v1alpha1.GetJWTRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "account_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:auth.v1alpha1.GetJWTRequest)
    private static final com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest DEFAULT_INSTANCE;
    static {
      GetJWTRequest defaultInstance = new GetJWTRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetJWTRequest.class, defaultInstance);
    }

    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetJWTRequest> PARSER;

    public static com.google.protobuf.Parser<GetJWTRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetJWTResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.v1alpha1.GetJWTResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string token = 1 [json_name = "token"];</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 1 [json_name = "token"];</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code auth.v1alpha1.GetJWTResponse}
   */
  public  static final class GetJWTResponse extends
      com.google.protobuf.GeneratedMessageLite<
          GetJWTResponse, GetJWTResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:auth.v1alpha1.GetJWTResponse)
      GetJWTResponseOrBuilder {
    private GetJWTResponse() {
      token_ = "";
    }
    public static final int TOKEN_FIELD_NUMBER = 1;
    private java.lang.String token_;
    /**
     * <code>string token = 1 [json_name = "token"];</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      return token_;
    }
    /**
     * <code>string token = 1 [json_name = "token"];</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(token_);
    }
    /**
     * <code>string token = 1 [json_name = "token"];</code>
     * @param value The token to set.
     */
    private void setToken(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      token_ = value;
    }
    /**
     * <code>string token = 1 [json_name = "token"];</code>
     */
    private void clearToken() {
      
      token_ = getDefaultInstance().getToken();
    }
    /**
     * <code>string token = 1 [json_name = "token"];</code>
     * @param value The bytes for token to set.
     */
    private void setTokenBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      token_ = value.toStringUtf8();
      
    }

    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code auth.v1alpha1.GetJWTResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.v1alpha1.GetJWTResponse)
        com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponseOrBuilder {
      // Construct using com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string token = 1 [json_name = "token"];</code>
       * @return The token.
       */
      @java.lang.Override
      public java.lang.String getToken() {
        return instance.getToken();
      }
      /**
       * <code>string token = 1 [json_name = "token"];</code>
       * @return The bytes for token.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTokenBytes() {
        return instance.getTokenBytes();
      }
      /**
       * <code>string token = 1 [json_name = "token"];</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        copyOnWrite();
        instance.setToken(value);
        return this;
      }
      /**
       * <code>string token = 1 [json_name = "token"];</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        copyOnWrite();
        instance.clearToken();
        return this;
      }
      /**
       * <code>string token = 1 [json_name = "token"];</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTokenBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:auth.v1alpha1.GetJWTResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "token_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:auth.v1alpha1.GetJWTResponse)
    private static final com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse DEFAULT_INSTANCE;
    static {
      GetJWTResponse defaultInstance = new GetJWTResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetJWTResponse.class, defaultInstance);
    }

    public static com.example.trainstationapp.data.grpc.auth.v1alpha1.AuthProto.GetJWTResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetJWTResponse> PARSER;

    public static com.google.protobuf.Parser<GetJWTResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
