// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: auth/v1alpha1/auth.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.trainstationapp.data.grpc.auth.v1alpha1;

