// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import ()

type Favorite struct {
	StationID string
	UserID    string
}

type Station struct {
	ID         string
	Commune    string
	YWgs84     float64
	XWgs84     float64
	Libelle    string
	Idgaia     string
	Voyageurs  string
	GeoPoint2d string
	CodeLigne  string
	XL93       float64
	CGeo       string
	RgTroncon  int64
	GeoShape   string
	Pk         string
	Idreseau   int64
	Departemen string
	YL93       float64
	Fret       string
}
