name: Skip on ignored paths / Android CI

on:
  pull_request:
    paths-ignore:
      - .github/workflows/android.yml
      - train-station-app/**

jobs:
  check-android:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No lint required"'

  test-android:
    runs-on: self-hosted
    steps:
      - run: 'echo "No test required"'

  build-android:
    runs-on: self-hosted
    steps:
      - run: 'echo "No build required"'

  package-apk-android:
    runs-on: self-hosted
    steps:
      - run: 'echo "No package apk required"'

  package-aab-android:
    runs-on: self-hosted
    steps:
      - run: 'echo "No package aab required"'
