name: Skip on ignored paths / Go CI

on:
  pull_request:
    paths-ignore:
      - .github/workflows/golang.yml
      - go/**

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No lint required"'

  test-go:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No test required"'

  build-go:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
