name: Android CI

on: push

defaults:
  run:
    working-directory: train-station-app

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

  test-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Test with Gradle
        run: |
          chmod +x gradlew
          ./gradlew test

  package-apk-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Import keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" > app/keystore.jks.asc
          gpg -d --passphrase "${{ secrets.DECRYPT_SHARED_KEY }}" --batch app/keystore.jks.asc >> app/keystore.jks
          echo "${{ secrets.KEY_PROPERTIES }}" | key.properties.asc
          gpg -d --passphrase "${{ secrets.DECRYPT_SHARED_KEY }}" --batch key.properties.asc >> key.properties

      - name: Package with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: app-apk
          path: app/build/outputs/apk/release/app-release.apk

  package-aab-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Bundle with Gradle
        run: |
          chmod +x gradlew
          ./gradlew app:bundleRelease
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: app-aab
          path: app/build/outputs/bundle/release/app-release.aab

  deploy-android:
    needs:
      - test-android
      - build-android
      - package-apk-android
      - package-aab-android
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app-apk
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app-aab

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-release.apk
            app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
