name: Android CI

on: push

defaults:
  run:
    working-directory: train-station-app

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Import keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
          DECRYPT_SHARED_KEY: ${{ secrets.DECRYPT_SHARED_KEY }}
        run: |
          echo "$KEYSTORE_BASE64" > app/keystore.jks.asc
          gpg -d --passphrase "$DECRYPT_SHARED_KEY" --batch app/keystore.jks.asc >> app/keystore.jks
          echo "$KEY_PROPERTIES" > key.properties.asc
          gpg -d --passphrase "$DECRYPT_SHARED_KEY" --batch key.properties.asc >> key.properties
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

  test-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Test with Gradle
        run: |
          chmod +x gradlew
          ./gradlew test

  package-apk-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Import keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
          DECRYPT_SHARED_KEY: ${{ secrets.DECRYPT_SHARED_KEY }}
        run: |
          echo "$KEYSTORE_BASE64" > app/keystore.jks.asc
          gpg -d --passphrase "$DECRYPT_SHARED_KEY" --batch app/keystore.jks.asc >> app/keystore.jks
          echo "$KEY_PROPERTIES" > key.properties.asc
          gpg -d --passphrase "$DECRYPT_SHARED_KEY" --batch key.properties.asc >> key.properties

      - name: Package with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: app-apk
          path: train-station-app/app/build/outputs/apk/release/app-release.apk

  package-aab-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Import keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
          DECRYPT_SHARED_KEY: ${{ secrets.DECRYPT_SHARED_KEY }}
        run: |
          echo "$KEYSTORE_BASE64" > app/keystore.jks.asc
          gpg -d --passphrase "$DECRYPT_SHARED_KEY" --batch app/keystore.jks.asc >> app/keystore.jks
          echo "$KEY_PROPERTIES" > key.properties.asc
          gpg -d --passphrase "$DECRYPT_SHARED_KEY" --batch key.properties.asc >> key.properties
      - name: Bundle with Gradle
        run: |
          chmod +x gradlew
          ./gradlew app:bundleRelease
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: app-aab
          path: train-station-app/app/build/outputs/bundle/release/app-release.aab

  deploy-android:
    needs:
      - test-android
      - build-android
      - package-apk-android
      - package-aab-android
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app-apk
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app-aab
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Build Changelog
        id: github_release
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          repo: Darkness4/train-station
          user: Darkness4
          project: train-station
          token: ${{ secrets.GITHUB_TOKEN }}
          excludeTagsRegex: ^(?!${{ env.TAG }}$).*$

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-release.apk
            app-release.aab
          body: ${{ steps.github_release.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
