name: Go CI

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:

defaults:
  run:
    working-directory: train-station-api-go

jobs:
  build-go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: Darkness4/train-station-api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
