name: Go CI

on: push

defaults:
  run:
    working-directory: train-station-api-go

jobs:
  build-go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: train-station-api-go/.
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          outputs: type=docker,dest=/tmp/image.tar
          tags: Darkness4/train-station-api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar

  deploy-go:
    needs: build-go
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/image.tar
          docker image ls -a

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        run: |
          docker push Darkness4/train-station-api:latest
