name: Go CI

on:
  push:
    paths:
      - .github/workflows/golang.yaml
      - train-station-api-go/**
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    paths:
      - .github/workflows/golang.yaml
      - train-station-api-go/**

defaults:
  run:
    working-directory: ./train-station-api-go

jobs:
  lint-go:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Download build-essential
        run: |
          sudo apt update -y
          sudo apt install -y build-essential

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.19'
          cache: true
          cache-dependency-path: train-station-api-go/go.sum

      - name: Download all Go modules
        run: |
          go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./train-station-api-go
          args: --timeout 5m

  test-go:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Download build-essential
        run: |
          sudo apt update -y
          sudo apt install -y build-essential

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.19'
          cache: true
          cache-dependency-path: train-station-api-go/go.sum

      - name: Download all Go modules
        run: |
          go mod download

      - name: Run tests
        run: go test -race -covermode=atomic -timeout=30s ./...

  build-go:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags') }}
        with:
          context: train-station-api-go
          file: ./train-station-api-go/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/darkness4/train-station-api:latest
          build-args: |
            VERSION=dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login to GHCR
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the oci compatible version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        run: |
          OCI_VERSION=$(echo ${GITHUB_REF#refs/*/} | sed 's/+/-/g')
          echo "VERSION=${OCI_VERSION}" >> $GITHUB_OUTPUT

      - name: Build and export
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v4
        with:
          context: train-station-api-go
          file: ./train-station-api-go/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/darkness4/train-station-api:latest
            ghcr.io/darkness4/train-station-api:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            ${{ steps.get_version.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
