name: Nest CI

on: [push, pull_request]

defaults:
  run:
    working-directory: train-station-api

jobs:
  build-nest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
        env:
          CI: true

  deploy-nest:
    needs: build-nest
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: release/api
          publish_dir: ./
