name: Nest CI

on: push

jobs:
  build-nest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: train-station-api
          file: ./train-station-api/Dockerfile
          platforms: linux/amd64
          outputs: type=docker,dest=/tmp/image-amd64.tar
          tags: ghcr.io/darkness4/train-station-api:nestjs

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: image-amd64
          path: /tmp/image-amd64.tar

  deploy-nest:
    needs:
      - build-nest
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image-amd64

      - name: Load image
        run: |
          docker load --input image-amd64.tar
          docker image ls -a

      - name: Login to GitHub Packages Docker Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username $GITHUB_ACTOR --password-stdin

      - name: Deploy
        run: |
          if echo "$GITHUB_REF" | grep -q 'refs/tags/'; then
            docker tag ghcr.io/darkness4/train-station-api:nestjs "ghcr.io/darkness4/train-station-api:nestjs-${GITHUB_REF#refs/*/}"
          fi
          docker push ghcr.io/darkness4/train-station-api --all-tags
