name: Svelte CI

on:
  push:
    paths:
      - .github/workflows/svelte.yaml
      - train-station-front/**
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    paths:
      - .github/workflows/svelte.yaml
      - train-station-front/**

defaults:
  run:
    working-directory: train-station-front

jobs:
  build-deploy-svelte:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: train-station-front
          file: ./train-station-front/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/darkness4/train-station-front:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login to GHCR
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the oci compatible version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        run: |
          OCI_VERSION=$(echo ${GITHUB_REF#refs/*/} | sed 's/+/-/g')
          echo ::set-output name=VERSION::${OCI_VERSION}

      - name: Build and export
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v4
        with:
          context: train-station-front
          file: ./train-station-front/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/darkness4/train-station-front:latest
            ghcr.io/darkness4/train-station-front:${{ steps.get_version.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
