// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/health/v1/health.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.trainstationapp.data.grpc.grpc.health.v1;

@kotlin.jvm.JvmName("-initializehealthListResponse")
public inline fun healthListResponse(block: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthListResponseKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse =
  com.example.trainstationapp.data.grpc.grpc.health.v1.HealthListResponseKt.Dsl._create(com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpc.health.v1.HealthListResponse`
 */
public object HealthListResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class StatusesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * statuses contains all the services and their respective status.
     * ```
     *
     * `map<string, .grpc.health.v1.HealthCheckResponse> statuses = 1 [json_name = "statuses"];`
     */
     public val statuses: com.google.protobuf.kotlin.DslMap<kotlin.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse, StatusesProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getStatusesMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.statusesMap
      )
    /**
     * ```
     * statuses contains all the services and their respective status.
     * ```
     *
     * `map<string, .grpc.health.v1.HealthCheckResponse> statuses = 1 [json_name = "statuses"];`
     */
    @kotlin.jvm.JvmName("putStatuses")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse, StatusesProxy>
      .put(key: kotlin.String, value: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse) {
         _builder.putStatuses(key, value)
       }
    /**
     * ```
     * statuses contains all the services and their respective status.
     * ```
     *
     * `map<string, .grpc.health.v1.HealthCheckResponse> statuses = 1 [json_name = "statuses"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setStatuses")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse, StatusesProxy>
      .set(key: kotlin.String, value: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse) {
         put(key, value)
       }
    /**
     * ```
     * statuses contains all the services and their respective status.
     * ```
     *
     * `map<string, .grpc.health.v1.HealthCheckResponse> statuses = 1 [json_name = "statuses"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeStatuses")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse, StatusesProxy>
      .remove(key: kotlin.String) {
         _builder.removeStatuses(key)
       }
    /**
     * ```
     * statuses contains all the services and their respective status.
     * ```
     *
     * `map<string, .grpc.health.v1.HealthCheckResponse> statuses = 1 [json_name = "statuses"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllStatuses")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse, StatusesProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse>) {
         _builder.putAllStatuses(map)
       }
    /**
     * ```
     * statuses contains all the services and their respective status.
     * ```
     *
     * `map<string, .grpc.health.v1.HealthCheckResponse> statuses = 1 [json_name = "statuses"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearStatuses")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse, StatusesProxy>
      .clear() {
         _builder.clearStatuses()
       }
  }
}
public inline fun com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse.copy(block: `com.example.trainstationapp.data.grpc.grpc.health.v1`.HealthListResponseKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse =
  `com.example.trainstationapp.data.grpc.grpc.health.v1`.HealthListResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
