// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: grpc/health/v1/health.proto
//
package com.example.trainstationapp.`data`.grpc.grpc.health.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.ServerOnlyStreamInterface
import com.connectrpc.StreamType

/**
 *  Health is gRPC's mechanism for checking whether a server is able to handle
 *  RPCs. Its semantics are documented in
 *  https://github.com/grpc/grpc/blob/master/doc/health-checking.md.
 */
public class HealthClient(
  private val client: ProtocolClientInterface,
) : HealthClientInterface {
  /**
   *  Check gets the health of the specified service. If the requested service
   *  is unknown, the call will fail with status NOT_FOUND. If the caller does
   *  not specify a service name, the server should respond with its overall
   *  health status.
   *
   *  Clients should set a deadline when calling Check, and can declare the
   *  server unhealthy if they do not receive a timely response.
   */
  override suspend fun check(request: HealthProto.HealthCheckRequest, headers: Headers): ResponseMessage<HealthProto.HealthCheckResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "grpc.health.v1.Health/Check",
      com.example.trainstationapp.`data`.grpc.grpc.health.v1.HealthProto.HealthCheckRequest::class,
      com.example.trainstationapp.`data`.grpc.grpc.health.v1.HealthProto.HealthCheckResponse::class,
      StreamType.UNARY,
    ),
  )


  /**
   *  List provides a non-atomic snapshot of the health of all the available
   *  services.
   *
   *  The server may respond with a RESOURCE_EXHAUSTED error if too many services
   *  exist.
   *
   *  Clients should set a deadline when calling List, and can declare the server
   *  unhealthy if they do not receive a timely response.
   *
   *  Clients should keep in mind that the list of health services exposed by an
   *  application can change over the lifetime of the process.
   */
  override suspend fun list(request: HealthProto.HealthListRequest, headers: Headers): ResponseMessage<HealthProto.HealthListResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "grpc.health.v1.Health/List",
      com.example.trainstationapp.`data`.grpc.grpc.health.v1.HealthProto.HealthListRequest::class,
      com.example.trainstationapp.`data`.grpc.grpc.health.v1.HealthProto.HealthListResponse::class,
      StreamType.UNARY,
    ),
  )


  /**
   *  Performs a watch for the serving status of the requested service.
   *  The server will immediately send back a message indicating the current
   *  serving status.  It will then subsequently send a new message whenever
   *  the service's serving status changes.
   *
   *  If the requested service is unknown when the call is received, the
   *  server will send a message setting the serving status to
   *  SERVICE_UNKNOWN but will *not* terminate the call.  If at some
   *  future point, the serving status of the service becomes known, the
   *  server will send a new message with the service's serving status.
   *
   *  If the call terminates with status UNIMPLEMENTED, then clients
   *  should assume this method is not supported and should not retry the
   *  call.  If the call terminates with any other status (including OK),
   *  clients should retry the call with appropriate exponential backoff.
   */
  override suspend fun watch(headers: Headers): ServerOnlyStreamInterface<HealthProto.HealthCheckRequest, HealthProto.HealthCheckResponse> = client.serverStream(
    headers,
    MethodSpec(
    "grpc.health.v1.Health/Watch",
      com.example.trainstationapp.`data`.grpc.grpc.health.v1.HealthProto.HealthCheckRequest::class,
      com.example.trainstationapp.`data`.grpc.grpc.health.v1.HealthProto.HealthCheckResponse::class,
      StreamType.SERVER,
    ),
  )

}
