// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/health/v1/health.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.trainstationapp.data.grpc.grpc.health.v1;

@kotlin.jvm.JvmName("-initializehealthListRequest")
public inline fun healthListRequest(block: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthListRequestKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest =
  com.example.trainstationapp.data.grpc.grpc.health.v1.HealthListRequestKt.Dsl._create(com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpc.health.v1.HealthListRequest`
 */
public object HealthListRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest = _builder.build()
  }
}
public inline fun com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest.copy(block: `com.example.trainstationapp.data.grpc.grpc.health.v1`.HealthListRequestKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest =
  `com.example.trainstationapp.data.grpc.grpc.health.v1`.HealthListRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

