// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/health/v1/health.proto
// Protobuf Java Version: 4.34.1

package com.example.trainstationapp.data.grpc.grpc.health.v1;

@com.google.protobuf.Generated
public final class HealthProto {
  private HealthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface HealthCheckRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.health.v1.HealthCheckRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string service = 1 [json_name = "service"];</code>
     * @return The service.
     */
    java.lang.String getService();
    /**
     * <code>string service = 1 [json_name = "service"];</code>
     * @return The bytes for service.
     */
    com.google.protobuf.ByteString
        getServiceBytes();
  }
  /**
   * Protobuf type {@code grpc.health.v1.HealthCheckRequest}
   */
  public  static final class HealthCheckRequest extends
      com.google.protobuf.GeneratedMessageLite<
          HealthCheckRequest, HealthCheckRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:grpc.health.v1.HealthCheckRequest)
      HealthCheckRequestOrBuilder {
    private HealthCheckRequest() {
      service_ = "";
    }
    public static final int SERVICE_FIELD_NUMBER = 1;
    private java.lang.String service_;
    /**
     * <code>string service = 1 [json_name = "service"];</code>
     * @return The service.
     */
    @java.lang.Override
    public java.lang.String getService() {
      return service_;
    }
    /**
     * <code>string service = 1 [json_name = "service"];</code>
     * @return The bytes for service.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServiceBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(service_);
    }
    /**
     * <code>string service = 1 [json_name = "service"];</code>
     * @param value The service to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setService(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      service_ = value;
    }
    /**
     * <code>string service = 1 [json_name = "service"];</code>
     */
    private void clearService() {

      service_ = getDefaultInstance().getService();
    }
    /**
     * <code>string service = 1 [json_name = "service"];</code>
     * @param value The bytes for service to set.
     */
    private void setServiceBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      service_ = value.toStringUtf8();

    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code grpc.health.v1.HealthCheckRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.health.v1.HealthCheckRequest)
        com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequestOrBuilder {
      // Construct using com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string service = 1 [json_name = "service"];</code>
       * @return The service.
       */
      @java.lang.Override
      public java.lang.String getService() {
        return instance.getService();
      }
      /**
       * <code>string service = 1 [json_name = "service"];</code>
       * @return The bytes for service.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getServiceBytes() {
        return instance.getServiceBytes();
      }
      /**
       * <code>string service = 1 [json_name = "service"];</code>
       * @param value The service to set.
       * @return This builder for chaining.
       */
      public Builder setService(
          java.lang.String value) {
        copyOnWrite();
        instance.setService(value);
        return this;
      }
      /**
       * <code>string service = 1 [json_name = "service"];</code>
       * @return This builder for chaining.
       */
      public Builder clearService() {
        copyOnWrite();
        instance.clearService();
        return this;
      }
      /**
       * <code>string service = 1 [json_name = "service"];</code>
       * @param value The bytes for service to set.
       * @return This builder for chaining.
       */
      public Builder setServiceBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setServiceBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:grpc.health.v1.HealthCheckRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "service_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:grpc.health.v1.HealthCheckRequest)
    private static final com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest DEFAULT_INSTANCE;
    static {
      HealthCheckRequest defaultInstance = new HealthCheckRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        HealthCheckRequest.class, defaultInstance);
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<HealthCheckRequest> PARSER;

    public static com.google.protobuf.Parser<HealthCheckRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface HealthCheckResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.health.v1.HealthCheckResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
     * @return The status.
     */
    com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.ServingStatus getStatus();
  }
  /**
   * Protobuf type {@code grpc.health.v1.HealthCheckResponse}
   */
  public  static final class HealthCheckResponse extends
      com.google.protobuf.GeneratedMessageLite<
          HealthCheckResponse, HealthCheckResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:grpc.health.v1.HealthCheckResponse)
      HealthCheckResponseOrBuilder {
    private HealthCheckResponse() {
    }
    /**
     * Protobuf enum {@code grpc.health.v1.HealthCheckResponse.ServingStatus}
     */
    public enum ServingStatus
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>SERVING = 1;</code>
       */
      SERVING(1),
      /**
       * <code>NOT_SERVING = 2;</code>
       */
      NOT_SERVING(2),
      /**
       * <pre>
       * Used only by the Watch method.
       * </pre>
       *
       * <code>SERVICE_UNKNOWN = 3;</code>
       */
      SERVICE_UNKNOWN(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>SERVING = 1;</code>
       */
      public static final int SERVING_VALUE = 1;
      /**
       * <code>NOT_SERVING = 2;</code>
       */
      public static final int NOT_SERVING_VALUE = 2;
      /**
       * <pre>
       * Used only by the Watch method.
       * </pre>
       *
       * <code>SERVICE_UNKNOWN = 3;</code>
       */
      public static final int SERVICE_UNKNOWN_VALUE = 3;


      @java.lang.Override
      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ServingStatus valueOf(int value) {
        return forNumber(value);
      }

      public static ServingStatus forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return SERVING;
          case 2: return NOT_SERVING;
          case 3: return SERVICE_UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ServingStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ServingStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ServingStatus>() {
              @java.lang.Override
              public ServingStatus findValueByNumber(int number) {
                return ServingStatus.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return ServingStatusVerifier.INSTANCE;
      }

      private static final class ServingStatusVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier
                  INSTANCE = new ServingStatusVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return ServingStatus.forNumber(number) != null;
              }
            };

      private final int value;

      private ServingStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:grpc.health.v1.HealthCheckResponse.ServingStatus)
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.ServingStatus getStatus() {
      com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.ServingStatus result = com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.ServingStatus.forNumber(status_);
      return result == null ? com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.ServingStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
     * @param value The status to set.
     */
    private void setStatus(com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.ServingStatus value) {
      status_ = value.getNumber();

    }
    /**
     * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
     */
    private void clearStatus() {

      status_ = 0;
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code grpc.health.v1.HealthCheckResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.health.v1.HealthCheckResponse)
        com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponseOrBuilder {
      // Construct using com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
       * @return The status.
       */
      @java.lang.Override
      public com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.ServingStatus getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
       * @param value The enum numeric value on the wire for status to set.
       * @throws IllegalArgumentException if UNRECOGNIZED is provided.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.ServingStatus value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1 [json_name = "status"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:grpc.health.v1.HealthCheckResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "status_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:grpc.health.v1.HealthCheckResponse)
    private static final com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse DEFAULT_INSTANCE;
    static {
      HealthCheckResponse defaultInstance = new HealthCheckResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        HealthCheckResponse.class, defaultInstance);
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<HealthCheckResponse> PARSER;

    public static com.google.protobuf.Parser<HealthCheckResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface HealthListRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.health.v1.HealthListRequest)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code grpc.health.v1.HealthListRequest}
   */
  public  static final class HealthListRequest extends
      com.google.protobuf.GeneratedMessageLite<
          HealthListRequest, HealthListRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:grpc.health.v1.HealthListRequest)
      HealthListRequestOrBuilder {
    private HealthListRequest() {
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code grpc.health.v1.HealthListRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.health.v1.HealthListRequest)
        com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequestOrBuilder {
      // Construct using com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:grpc.health.v1.HealthListRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;
            java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:grpc.health.v1.HealthListRequest)
    private static final com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest DEFAULT_INSTANCE;
    static {
      HealthListRequest defaultInstance = new HealthListRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        HealthListRequest.class, defaultInstance);
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<HealthListRequest> PARSER;

    public static com.google.protobuf.Parser<HealthListRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface HealthListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.health.v1.HealthListResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
     */
    int getStatusesCount();
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
     */
    boolean containsStatuses(
        java.lang.String key);
    /**
     * Use {@link #getStatusesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse>
    getStatuses();
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
     */
    java.util.Map<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse>
    getStatusesMap();
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
     */

    /* nullable */
com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse getStatusesOrDefault(
        java.lang.String key,
        /* nullable */
com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse defaultValue);
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
     */

    com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse getStatusesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code grpc.health.v1.HealthListResponse}
   */
  public  static final class HealthListResponse extends
      com.google.protobuf.GeneratedMessageLite<
          HealthListResponse, HealthListResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:grpc.health.v1.HealthListResponse)
      HealthListResponseOrBuilder {
    private HealthListResponse() {
    }
    public static final int STATUSES_FIELD_NUMBER = 1;
    private static final class StatusesDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse.getDefaultInstance());
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse> statuses_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse>
    internalGetStatuses() {
      return statuses_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse>
    internalGetMutableStatuses() {
      if (!statuses_.isMutable()) {
        statuses_ = statuses_.mutableCopy();
      }
      return statuses_;
    }
    @java.lang.Override

    public int getStatusesCount() {
      return internalGetStatuses().size();
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
     */
    @java.lang.Override

    public boolean containsStatuses(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return internalGetStatuses().containsKey(key);
    }
    /**
     * Use {@link #getStatusesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse> getStatuses() {
      return getStatusesMap();
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse> getStatusesMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetStatuses());
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
     */
    @java.lang.Override

    public /* nullable */
com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse getStatusesOrDefault(
        java.lang.String key,
        /* nullable */
com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse> map =
          internalGetStatuses();
      com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse v = map.get(key);
      return v != null ? v : defaultValue;
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
     */
    @java.lang.Override

    public com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse getStatusesOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse> map =
          internalGetStatuses();
      com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse v = map.get(key);
      if (v == null) {
        throw new java.lang.IllegalArgumentException();
      }
      return v;
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
     */
    private java.util.Map<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse>
    getMutableStatusesMap() {
      return internalGetMutableStatuses();
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code grpc.health.v1.HealthListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.health.v1.HealthListResponse)
        com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponseOrBuilder {
      // Construct using com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      @java.lang.Override

      public int getStatusesCount() {
        return instance.getStatusesMap().size();
      }
      /**
       * <pre>
       * statuses contains all the services and their respective status.
       * </pre>
       *
       * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
       */
      @java.lang.Override

      public boolean containsStatuses(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        return instance.getStatusesMap().containsKey(key);
      }

      public Builder clearStatuses() {
        copyOnWrite();
        instance.getMutableStatusesMap().clear();
        return this;
      }
      /**
       * <pre>
       * statuses contains all the services and their respective status.
       * </pre>
       *
       * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
       */

      public Builder removeStatuses(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        copyOnWrite();
        instance.getMutableStatusesMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getStatusesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse> getStatuses() {
        return getStatusesMap();
      }
      /**
       * <pre>
       * statuses contains all the services and their respective status.
       * </pre>
       *
       * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse> getStatusesMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getStatusesMap());
      }
      /**
       * <pre>
       * statuses contains all the services and their respective status.
       * </pre>
       *
       * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
       */
      @java.lang.Override

      public /* nullable */
com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse getStatusesOrDefault(
          java.lang.String key,
          /* nullable */
com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse defaultValue) {
        java.lang.Class<?> keyClass = key.getClass();
        java.util.Map<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse> map =
            instance.getStatusesMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * statuses contains all the services and their respective status.
       * </pre>
       *
       * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
       */
      @java.lang.Override

      public com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse getStatusesOrThrow(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        java.util.Map<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse> map =
            instance.getStatusesMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <pre>
       * statuses contains all the services and their respective status.
       * </pre>
       *
       * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
       */
      public Builder putStatuses(
          java.lang.String key,
          com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse value) {
        java.lang.Class<?> keyClass = key.getClass();
        java.lang.Class<?> valueClass = value.getClass();
        copyOnWrite();
        instance.getMutableStatusesMap().put(key, value);
        return this;
      }
      /**
       * <pre>
       * statuses contains all the services and their respective status.
       * </pre>
       *
       * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1 [json_name = "statuses"];</code>
       */
      public Builder putAllStatuses(
          java.util.Map<java.lang.String, com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckResponse> values) {
        copyOnWrite();
        instance.getMutableStatusesMap().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:grpc.health.v1.HealthListResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "statuses_",
              StatusesDefaultEntryHolder.defaultEntry,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u00012";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:grpc.health.v1.HealthListResponse)
    private static final com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse DEFAULT_INSTANCE;
    static {
      HealthListResponse defaultInstance = new HealthListResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        HealthListResponse.class, defaultInstance);
    }

    public static com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<HealthListResponse> PARSER;

    public static com.google.protobuf.Parser<HealthListResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
