// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/health/v1/health.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.trainstationapp.data.grpc.grpc.health.v1;

@kotlin.jvm.JvmName("-initializehealthCheckRequest")
public inline fun healthCheckRequest(block: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthCheckRequestKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest =
  com.example.trainstationapp.data.grpc.grpc.health.v1.HealthCheckRequestKt.Dsl._create(com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpc.health.v1.HealthCheckRequest`
 */
public object HealthCheckRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest = _builder.build()

    /**
     * `string service = 1 [json_name = "service"];`
     */
    public var service: kotlin.String
      @kotlin.jvm.JvmName("getService")
        get() = _builder.service
      @kotlin.jvm.JvmName("setService")
        set(value) {
        _builder.service = value
      }
    /**
     * `string service = 1 [json_name = "service"];`
     */
    public fun clearService() {
      _builder.clearService()
    }
  }
}
public inline fun com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest.copy(block: `com.example.trainstationapp.data.grpc.grpc.health.v1`.HealthCheckRequestKt.Dsl.() -> kotlin.Unit): com.example.trainstationapp.data.grpc.grpc.health.v1.HealthProto.HealthCheckRequest =
  `com.example.trainstationapp.data.grpc.grpc.health.v1`.HealthCheckRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

