// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: grpc/health/v1/health.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.trainstationapp.data.grpc.grpc.health.v1;

